### ISSUE TITLE
Animations broken

### ISSUE THREAD

**Issue by 3052** [jottocraft/dtps#1]
**Describe the bug**
No animations in bg color when moving between clases

**Repo steps**
switch classes

**Expected behavior:**
cool animation thingy

**Actual behavior:**
NO ANIMATION AND DELAYED COLOR SWAP

**Desktop (please complete the following information):**
 - OS with version: [e.g. Windows 10, macOS Mojave]
-CHROMEBOOK
-browser: WHAT DO YOU THINK CHROEM

PS, if you cant tell im hangry right now yeah thats what i need is a snickers

**Comment by jottocraft** [comment]
this feature is currently incomplete. This was previously implemented in an earlier version of dtps (beta) but was removed due to a bug that prevented the class content buttons from working. this issue is known and a fix is already being developed, will be released in v0.2.0 (will update roadmap to reflect). project dtps is still in beta so you should expect many things to not work.
