### ISSUE TITLE
Groups for classes

### ISSUE THREAD

**Issue by guidepupguy** [jottocraft/dtps#22]
Can you add the ability to open class groups, as I have a group that I need to access, and acts as a subclass.

**Comment by jottocraft** [comment]
Class groups are a bit weird in Canvas. I want to add support for this in the future, but I want to make sure I get the UI right and support everything classes support. I'm not sure when I'll get around to adding it, but I'll try to get it in by the end of the year.

**Comment by jottocraft** [comment]
Canvas groups are now supported in Power+ v3 discussions, since discussions is the most common use case for Canvas groups. In this new version, opening a discussion that is associated with a group will load the group discussion instead of the class discussion. This feature will be released with the first beta of Power+ v3 on June 8th.

Unfortunately, Power+ will never have full group support due to its complexity and low priority, so this will probably be as far as group support will go in Power+.
