### ISSUE TITLE
[DTPS] Error fetching user and classes at dtps.init 

### ISSUE THREAD

**Issue by ABucket** [jottocraft/dtps#39]
Hi, when I install the extension and go to https://www.instructure.com/power+/ it keep redirecting like this:
![image](https://user-images.githubusercontent.com/82869104/148692408-3f791d11-ff2b-420f-9366-5f5aa1601108.png)
and in my console, there is some info:
[DTPS] Error fetching user and classes at dtps.init {action: 'login', redirectURL: '/?dtpsLogin=true'}
[DTPS Chrome] Redirecting after login...

**Comment by jottocraft** [comment]
Power+ needs to be loaded through your institution's instructure.com subdomain (the same domain you use to access Canvas normally, e.g. canvas.instructure.com). With Power+ installed, you should see a "Power+" button in your Canvas sidebar that should take you to the correct URL.
![image](https://user-images.githubusercontent.com/11508240/148697857-63dfb757-e9a6-4b5b-9b67-6efabdb9326a.png)

**Comment by ABucket** [comment]
thx for your reply, but my school canvas have it's own domain and it is not the subdomain under instructure.

**Comment by jottocraft** [comment]
Power+ doesn't fully support self-hosted Canvas instances right now. Unfortunately, I can't update the Chrome extension to load Power+ on arbitrary domains since this would require permissions to modify all website data.

However, you can still load Power+ without the extension. I've copied the Power+ extension code into a Userscript that you get install from Greasy Fork [here](https://greasyfork.org/en/scripts/438558-power-userscript-loader). Once installed, you'll need to edit the `@match` rule on line 11 and replace `*.instructure.com` with the domain of your Canvas instance. Then you should be able to use Power+ normally.

**Comment by ABucket** [comment]
Thanks! It works!
